# Generated by Django 5.2 on 2025-05-25 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='fecha_envio',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='admin_visto',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='asunto',
        ),
        migrations.AddField(
            model_name='contacto',
            name='admin_responde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_resueltos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='estado',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('VISTO', 'Visto'), ('RESUELTO', 'Resuelto')], default='ENVIADO', max_length=10),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_enviados', to=settings.AUTH_USER_MODEL),
        ),
    ]
