# Generated by Django 5.2 on 2025-05-25 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_fecha_envio_contacto_fecha_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Mensaje de Contacto', 'verbose_name_plural': 'Mensajes de Contacto'},
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='admin_responde',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(default='Sin asunto', max_length=200, verbose_name='Asunto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='Leído'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
